---
title       : Motor Trend
subtitle    : Data Analysis
author      : Ashish Sehgal
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Mtcars DataSet


1. The data was extracted from the 1974 Motor Trend US magazine.

2. Data has 32 Observations with 11 Variables.

3. Source: Henderson and Velleman (1981).

--- .class #id 

## Brief discription of dataset


```{r}
library(datasets)
str(mtcars)

```

--- .class #id 
## The APP

# App has three panel

1. Details:includes the details of the data set.

2. Analysis: Main Analysis of all the variable w.r.t variable mpg.

3. SourceCode: Includes the source code file link to github.

--- .class #id 
## Analysis Part

- Here we are analysing w.r.t "mpg"" vaiable so we have kept this as fixed and a dropbox is provide where we can select the variable w.r.t whome we need to analyse.

- Tabs are provided for *Boxplot* and *Regression Model* of selected variable in Dropbox with mpg.

- checkbox is provide to show Boxplot's outliers.

- plot: shows boxplot or liner regresstion model of variables.

--- .class #id 

## Visit the app


Visit the project at

(https://ashishsehgal.shinyapps.io/Shiny_project)

The Code is Open Source at

(https://github.com/AshishSehgal/Shiny_project)


